FROM golang:1.26.0-alpine3.22 AS build
WORKDIR /src

COPY go.mod go.sum ./
#RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o /out/pgrwl-ui ./cmd/pgrwl-ui

FROM alpine:3.21.5
RUN adduser -D -H -u 10001 pgrwl
USER pgrwl
COPY --from=build /out/pgrwl-ui /usr/local/bin/pgrwl-ui

EXPOSE 8080

ENTRYPOINT ["pgrwl-ui"]
