---
main:
  listen_port: 7070
  directory: wals

receiver:
  slot: pgrwl_v5
  uploader:
    sync_interval: 10s
    max_concurrency: 4

devconfig:
  pprof:
    enable: true

log:
  level: info
  format: pretty
  add_source: true

storage:
  name: "local"
#  compression:
#    algo: gzip
#  encryption:
#    algo: aes-256-gcm
#    pass: qwerty123

backup:
  cron: "* * * * *"

retention:
  enable: true
  type: recovery_window
  value: "5m"
  keep_last: 1
