---
name: Integration Tests (localdev)

on:
  push:
    branches: &branches
      - "master"
      - "release/**"
    paths-ignore: &paths-ignore
      - ".run/**"
      - ".vscode/**"
      - "docs/**"
      - "examples/**"
      - "charts/**"
      - "hack/**"
      - "scripts/**"
      - "ui/static/**"
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
      - "Makefile"
      - ".golangci.yml"
      - "docker-compose.yml"
  pull_request:
    branches: *branches
    paths-ignore: *paths-ignore
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run tests
        run: |
          make test-integ-localdev
